module_pm = "PM"

link_pm = "%s PMs"
folder = "Folder"

############
# Overview #
############
mt_pm_overview = "PM Center"
md_pm_overview = "Show an overview of your PMs"

########
# Send #
########
mt_pm_send = "Send PM"
md_pm_send = "Send a PM to a user. This works across connectors."
msg_pm_sent = "The PM to %s has been sent successfully."

###########
# Welcome #
###########
welcome_pm_title = "Welcome!"
welcome_pm_body = "Hello %s<br/>Welcome to %s.<br/><br/>"

########
# View #
########
mt_pm_view = "Read PM"
md_pm_view = "Read a PM for this website."

########
# Next #
########
mt_pm_next = "Next Unread PM"
md_pm_next = "Read the next unread pm and mark it read."
msg_no_more_new_pm = "There are no unread pm for you."

mt_pm_folder = "PM Folder"
md_pm_folder = "Show a PM Folder like inbox(1) and outbox(2)"
